# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(386, 365)
        Dialog.setStyleSheet("background-color: #222222;")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(60, 70, 81, 21))
        self.radioButton.setStyleSheet("color: #4DFF00;\n"
"font: 10pt \"Century Gothic\";")
        self.radioButton.setObjectName("radioButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 0, 161, 51))
        self.label.setStyleSheet("color: #ccc;\n"
"font: 5 22pt \"Century Gothic\";\n"
"")
        self.label.setObjectName("label")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(270, 70, 41, 21))
        self.radioButton_2.setStyleSheet("color: #4DFF00;\n"
"font: 10pt \"Century Gothic\";")
        self.radioButton_2.setObjectName("radioButton_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(160, 130, 201, 41))
        self.lineEdit.setStyleSheet("border: none;\n"
"color: #4DFF00;\n"
"font: 10pt \"Century Gothic\";")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 141, 21))
        self.label_2.setStyleSheet("color: #4DFF00;\n"
"font: 10pt \"Century Gothic\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(330, 10, 47, 13))
        self.label_3.setStyleSheet("color: #ccc;\n"
"font: 5 8pt \"Century Gothic\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(90, 270, 221, 61))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    font: 75 11pt \"Century Gothic\";\n"
"    color: #4DFF00;\n"
"    background-color: #414141;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #40D400;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #6FFF30;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label_4.setStyleSheet("color: #ccc;\n"
"font: 5 8pt \"Century Gothic\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 331, 21))
        self.label_5.setStyleSheet("color: #4DFF00;\n"
"font: 10pt \"Century Gothic\";")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.radioButton.setText(_translate("Dialog", "Insagram"))
        self.label.setText(_translate("Dialog", "HackSploit"))
        self.radioButton_2.setText(_translate("Dialog", "VK"))
        self.label_2.setText(_translate("Dialog", "Ссылка на страницу:"))
        self.label_3.setText(_translate("Dialog", "version: 1"))
        self.pushButton.setText(_translate("Dialog", "Взломать"))
        self.label_4.setText(_translate("Dialog", "By: ADN"))
        self.label_5.setText(_translate("Dialog", "Статус:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
